name: Hub CI

on:
  pull_request:
    types: [opened]
    branches: ["master"]

jobs:
  lint-and-test-app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Yarn
        run: sudo npm install -g yarn
        env:
          CI: true
      - name: Install dependencies
        run: yarn
        env:
          CI: true
      - name: Prettier
        run: yarn format
        env:
          CI: true
      - name: Type Check
        run: yarn tsc
        env:
          CI: true
      - name: Test Build
        run: yarn build
        env:
          CI: true
